name: Test
on: [pull_request]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - run: npm ci
      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest
      - name: Run reviewdog
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm run lintorg | reviewdog -f=eslint -reporter=github-pr-review -filter-mode=diff_context -fail-on-error=true
      # - uses: reviewdog/action-eslint@v1
      #   with:
      #     reporter: github-pr-review
      #     eslint_flags: 'src/'
